# Catálogo Nacional de Estaciones del IDEAM

Se realizó un análisis (por tipología y estado) de las Estaciones Agrometeorológicas que se disponen en Colombia, reportadas por el Instituto de Hidrología, Meteorología y Estudios Ambientales (IDEAM), Centrando la atención en las estaciones que se encuentran activas en el departamento de Santander.

# Importar paquetes

In [1]:
import pandas as pd                  
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()

## Estaciones agrometeorológicas por departamento a nivel nacional

Nos centraremos en las estaciones que se encuentran activas a la fecha

In [3]:
df = pd.read_csv('C:\\Users\\castro.do\\OneDrive - Procter and Gamble\\Desktop\\Universidad\\Datasets\\Estaciones IDEAM\\Estaciones_IDEAM.csv')
df['Numero de Estaciones'] = 1

## Estado de las estaciones agrometeorológicas a nivel nacional

In [4]:
Estaciones_Estado = df.groupby(['Estado'])['Numero de Estaciones'].sum().reset_index()
Estaciones_Estado['%'] = (Estaciones_Estado['Numero de Estaciones'] /  Estaciones_Estado['Numero de Estaciones'].sum())*100
Estaciones_Estado = Estaciones_Estado.sort_values('%',ascending=False)
Estaciones_Estado = Estaciones_Estado.reset_index(drop=True)
Estaciones_Estado

             Estado  Numero de Estaciones          %
0            Activa                  5491  61.194695
1        Suspendida                  3439  38.326089
2  En Mantenimiento                    43   0.479215

## Estaciones agrometeorológicas activas por departamento a nivel nacional

In [5]:
Estaciones_Departamento = df
Estaciones_Departamento = Estaciones_Departamento.loc[Estaciones_Departamento['Estado'] == 'Activa']
Estaciones_Departamento = Estaciones_Departamento.groupby(['Departamento'])['Numero de Estaciones'].sum().reset_index()
Estaciones_Departamento['%'] = (Estaciones_Departamento['Numero de Estaciones'] /  Estaciones_Departamento['Numero de Estaciones'].sum())*100
Estaciones_Departamento = Estaciones_Departamento.sort_values('%',ascending=False)
Estaciones_Departamento = Estaciones_Departamento.reset_index(drop=True)
Estaciones_Departamento

,Departamento,Numero de Estaciones,%
0,Cundinamarca,804,14.642142
1,Antioquia,713,12.984884
2,Valle del Cauca,577,10.508104
3,Boyacá,326,5.936988
4,Caldas,323,5.882353
5,Santander,273,4.971772
6,Bogotá,250,4.552905
7,Cauca,236,4.297942
8,Tolima,209,3.806228
9,Huila,176,3.205245
10,Norte de Santander,143,2.604262
11,RIsaralda,143,2.604262
12,Bolívar,138,2.513203
13,Nariño,118,2.148971
14,Meta,105,1.912220
15,La Guajira,103,1.875797
16,Magdalena,103,1.875797
17,Cesar,96,1.748315
18,Córdoba,93,1.693681
19,Quindío,89,1.620834
20,Chocó,72,1.311237
21,Putumayo,63,1.147332
22,Casanare,56,1.019851
23,Sucre,51,0.928793
24,Atlantico,42,0.764888
25,Amazonas,40,0.728465
26,Vichada,39,0.710253
27,Caquetá,34,0.619195
28,Arauca,20,0.364232
29,"Archipiélago de San Andres, Providencia y Sant...",18,0.327809
30,Vaupes,16,0.291386
31,Guainía,12,0.218539
32,Guaviare,10,0.182116

## Estaciones agrometeorológicas activas por tipo a nivel nacional

In [6]:
Estaciones_Categoria = df
Estaciones_Categoria = Estaciones_Categoria.loc[Estaciones_Categoria['Estado'] == 'Activa']
Estaciones_Categoria = Estaciones_Categoria.groupby(['Categoria'])['Numero de Estaciones'].sum().reset_index()
Estaciones_Categoria['%'] = (Estaciones_Categoria['Numero de Estaciones'] /  Estaciones_Categoria['Numero de Estaciones'].sum())*100
Estaciones_Categoria = Estaciones_Categoria.sort_values('%',ascending=False)
Estaciones_Categoria = Estaciones_Categoria.reset_index(drop=True)
Estaciones_Categoria

                 Categoria  Numero de Estaciones          %
0            Pluviométrica                  2074  37.770898
1             Limnimétrica                   898  16.354034
2             Limnigráfica                   853  15.534511
3      Climática Principal                   576  10.489893
4            Pluviográfica                   460   8.377345
5      Climática Ordinaria                   401   7.302859
6   Meteorológica Especial                    94   1.711892
7        Agrometeorológica                    57   1.038062
8             Mareográfica                    31   0.564560
9      Sinóptica Principal                    31   0.564560
10             Radio Sonda                    11   0.200328
11    Sinóptica Secundaria                     5   0.091058

## Estaciones agrometeorológicas por estado en el departamento de Santander

In [7]:
Estaciones_Estado_Santander = df
Estaciones_Estado_Santander = Estaciones_Estado_Santander.loc[Estaciones_Estado_Santander['Departamento'] == 'Santander']
Estaciones_Estado_Santander = Estaciones_Estado_Santander.groupby(['Estado'])['Numero de Estaciones'].sum().reset_index()
Estaciones_Estado_Santander['%'] = (Estaciones_Estado_Santander['Numero de Estaciones'] /  Estaciones_Estado_Santander['Numero de Estaciones'].sum())*100
Estaciones_Estado_Santander = Estaciones_Estado_Santander.sort_values('%',ascending=False)
Estaciones_Estado_Santander = Estaciones_Estado_Santander.reset_index(drop=True)
Estaciones_Estado_Santander

             Estado  Numero de Estaciones          %
0            Activa                   273  57.716702
1        Suspendida                   199  42.071882
2  En Mantenimiento                     1   0.211416

## Estaciones agrometeorológicas activas por tipo en el departamento de Santander

In [9]:
Estaciones_Categoria_Santander = df
Estaciones_Categoria_Santander = Estaciones_Categoria_Santander.loc[Estaciones_Categoria_Santander['Estado'] == 'Activa']
Estaciones_Categoria_Santander = Estaciones_Categoria_Santander.loc[Estaciones_Categoria_Santander['Departamento'] == 'Santander']
Estaciones_Categoria_Santander = Estaciones_Categoria_Santander.groupby(['Categoria'])['Numero de Estaciones'].sum().reset_index()
Estaciones_Categoria_Santander['%'] = (Estaciones_Categoria_Santander['Numero de Estaciones'] /  Estaciones_Categoria_Santander['Numero de Estaciones'].sum())*100
Estaciones_Categoria_Santander = Estaciones_Categoria_Santander.sort_values('%',ascending=False)
Estaciones_Categoria_Santander = Estaciones_Categoria_Santander.reset_index(drop=True)
Estaciones_Categoria_Santander

                Categoria  Numero de Estaciones          %
0           Pluviométrica                   146  53.479853
1            Limnimétrica                    42  15.384615
2     Climática Principal                    24   8.791209
3     Climática Ordinaria                    21   7.692308
4            Limnigráfica                    21   7.692308
5           Pluviográfica                    11   4.029304
6       Agrometeorológica                     3   1.098901
7  Meteorológica Especial                     2   0.732601
8     Sinóptica Principal                     2   0.732601
9             Radio Sonda                     1   0.366300